---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 8983, host: 8888}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[solrcloud_test::prerun]
      - recipe[solrcloud::default]
    attributes:
      solrcloud:
        zk_run: true
